name: Publish Release

on:
  release:
    types: [published]


jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: npm ci
      - run: npm run build
      - name: Generate changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.1.1
        with:
          token: ${{ secrets.ACTIONS_TOKEN}}
          output: CHANGELOG.md
      - name: Write changelog
        run: |
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Changelog"
          git push -u origin HEAD:master
